name: alt text summary

on: [push]

jobs:
  alt text summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Open to see number of occurences
      run: grep ALT-TEXT-TO-BE-DETERMINED text/*.* exercises/*.* | wc -l
    - name: Open to see number of files with occurences
      run: grep ALT-TEXT-TO-BE-DETERMINED -l text/*.* exercises/*.* | wc -l
    - name: Open to see files with occurences and their counts
      run: grep ALT-TEXT-TO-BE-DETERMINED -c text/*.* exercises/*.* | grep -v :0
